// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msg_wrapper.proto
// Protobuf C++ Version: 6.30.2

#ifndef msg_5fwrapper_2eproto_2epb_2eh
#define msg_5fwrapper_2eproto_2epb_2eh

#include <limits>
#include "mqas/macro.h"
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6030002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_msg_5fwrapper_2eproto MQAS_EXTERN

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct MQAS_EXTERN TableStruct_msg_5fwrapper_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
MQAS_EXTERN extern const ::google::protobuf::internal::DescriptorTable descriptor_table_msg_5fwrapper_2eproto;
}  // extern "C"
namespace mqas {
namespace core {
namespace proto {
class MsgWrapper;
struct MsgWrapperDefaultTypeInternal;
MQAS_EXTERN extern MsgWrapperDefaultTypeInternal _MsgWrapper_default_instance_;
MQAS_EXTERN extern const ::google::protobuf::internal::ClassDataFull MsgWrapper_class_data_;
}  // namespace proto
}  // namespace core
}  // namespace mqas
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace mqas {
namespace core {
namespace proto {

// ===================================================================


// -------------------------------------------------------------------

class MQAS_EXTERN MsgWrapper final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mqas.core.proto.MsgWrapper) */ {
 public:
  inline MsgWrapper() : MsgWrapper(nullptr) {}
  ~MsgWrapper() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MsgWrapper* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MsgWrapper));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MsgWrapper(::google::protobuf::internal::ConstantInitialized);

  inline MsgWrapper(const MsgWrapper& from) : MsgWrapper(nullptr, from) {}
  inline MsgWrapper(MsgWrapper&& from) noexcept
      : MsgWrapper(nullptr, std::move(from)) {}
  inline MsgWrapper& operator=(const MsgWrapper& from) {
    CopyFrom(from);
    return *this;
  }
  inline MsgWrapper& operator=(MsgWrapper&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MsgWrapper& default_instance() {
    return *reinterpret_cast<const MsgWrapper*>(
        &_MsgWrapper_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(MsgWrapper& a, MsgWrapper& b) { a.Swap(&b); }
  inline void Swap(MsgWrapper* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MsgWrapper* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MsgWrapper* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MsgWrapper>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MsgWrapper& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MsgWrapper& from) { MsgWrapper::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MsgWrapper* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mqas.core.proto.MsgWrapper"; }

 protected:
  explicit MsgWrapper(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  MsgWrapper(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const MsgWrapper& from);
  MsgWrapper(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, MsgWrapper&& from) noexcept
      : MsgWrapper(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMsgBodyFieldNumber = 3,
    kMsgIdFieldNumber = 1,
    kBodyLenFieldNumber = 2,
  };
  // bytes msg_body = 3;
  void clear_msg_body() ;
  const std::string& msg_body() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_msg_body(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_msg_body();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_msg_body();
  void set_allocated_msg_body(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_msg_body() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_msg_body(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_msg_body();

  public:
  // uint32 msg_id = 1;
  void clear_msg_id() ;
  ::uint32_t msg_id() const;
  void set_msg_id(::uint32_t value);

  private:
  ::uint32_t _internal_msg_id() const;
  void _internal_set_msg_id(::uint32_t value);

  public:
  // uint32 body_len = 2;
  void clear_body_len() ;
  ::uint32_t body_len() const;
  void set_body_len(::uint32_t value);

  private:
  ::uint32_t _internal_body_len() const;
  void _internal_set_body_len(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:mqas.core.proto.MsgWrapper)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const MsgWrapper& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr msg_body_;
    ::uint32_t msg_id_;
    ::uint32_t body_len_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msg_5fwrapper_2eproto;
};

MQAS_EXTERN extern const ::google::protobuf::internal::ClassDataFull MsgWrapper_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// MsgWrapper

// uint32 msg_id = 1;
inline void MsgWrapper::clear_msg_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_id_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::uint32_t MsgWrapper::msg_id() const {
  // @@protoc_insertion_point(field_get:mqas.core.proto.MsgWrapper.msg_id)
  return _internal_msg_id();
}
inline void MsgWrapper::set_msg_id(::uint32_t value) {
  _internal_set_msg_id(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:mqas.core.proto.MsgWrapper.msg_id)
}
inline ::uint32_t MsgWrapper::_internal_msg_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.msg_id_;
}
inline void MsgWrapper::_internal_set_msg_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_id_ = value;
}

// uint32 body_len = 2;
inline void MsgWrapper::clear_body_len() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.body_len_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::uint32_t MsgWrapper::body_len() const {
  // @@protoc_insertion_point(field_get:mqas.core.proto.MsgWrapper.body_len)
  return _internal_body_len();
}
inline void MsgWrapper::set_body_len(::uint32_t value) {
  _internal_set_body_len(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:mqas.core.proto.MsgWrapper.body_len)
}
inline ::uint32_t MsgWrapper::_internal_body_len() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.body_len_;
}
inline void MsgWrapper::_internal_set_body_len(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.body_len_ = value;
}

// bytes msg_body = 3;
inline void MsgWrapper::clear_msg_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_body_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& MsgWrapper::msg_body() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mqas.core.proto.MsgWrapper.msg_body)
  return _internal_msg_body();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MsgWrapper::set_msg_body(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.msg_body_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mqas.core.proto.MsgWrapper.msg_body)
}
inline std::string* PROTOBUF_NONNULL MsgWrapper::mutable_msg_body()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_msg_body();
  // @@protoc_insertion_point(field_mutable:mqas.core.proto.MsgWrapper.msg_body)
  return _s;
}
inline const std::string& MsgWrapper::_internal_msg_body() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.msg_body_.Get();
}
inline void MsgWrapper::_internal_set_msg_body(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.msg_body_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL MsgWrapper::_internal_mutable_msg_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.msg_body_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE MsgWrapper::release_msg_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mqas.core.proto.MsgWrapper.msg_body)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.msg_body_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.msg_body_.Set("", GetArena());
  }
  return released;
}
inline void MsgWrapper::set_allocated_msg_body(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.msg_body_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.msg_body_.IsDefault()) {
    _impl_.msg_body_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mqas.core.proto.MsgWrapper.msg_body)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace core
}  // namespace mqas


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // msg_5fwrapper_2eproto_2epb_2eh
