// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: say_hello.proto
// Protobuf C++ Version: 6.30.2

#include "say_hello.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace proto {

inline constexpr SayHelloMsg2::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR SayHelloMsg2::SayHelloMsg2(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SayHelloMsg2_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SayHelloMsg2DefaultTypeInternal {
  PROTOBUF_CONSTEXPR SayHelloMsg2DefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SayHelloMsg2DefaultTypeInternal() {}
  union {
    SayHelloMsg2 _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SayHelloMsg2DefaultTypeInternal _SayHelloMsg2_default_instance_;

inline constexpr SayHelloMsg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR SayHelloMsg::SayHelloMsg(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SayHelloMsg_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SayHelloMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SayHelloMsgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SayHelloMsgDefaultTypeInternal() {}
  union {
    SayHelloMsg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SayHelloMsgDefaultTypeInternal _SayHelloMsg_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR SayByeMsg2::SayByeMsg2(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(SayByeMsg2_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct SayByeMsg2DefaultTypeInternal {
  PROTOBUF_CONSTEXPR SayByeMsg2DefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SayByeMsg2DefaultTypeInternal() {}
  union {
    SayByeMsg2 _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SayByeMsg2DefaultTypeInternal _SayByeMsg2_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR SayByeMsg::SayByeMsg(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(SayByeMsg_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct SayByeMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SayByeMsgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SayByeMsgDefaultTypeInternal() {}
  union {
    SayByeMsg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SayByeMsgDefaultTypeInternal _SayByeMsg_default_instance_;

inline constexpr RespSayByeMsg2::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR RespSayByeMsg2::RespSayByeMsg2(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RespSayByeMsg2_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RespSayByeMsg2DefaultTypeInternal {
  PROTOBUF_CONSTEXPR RespSayByeMsg2DefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RespSayByeMsg2DefaultTypeInternal() {}
  union {
    RespSayByeMsg2 _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RespSayByeMsg2DefaultTypeInternal _RespSayByeMsg2_default_instance_;

inline constexpr RespSayByeMsg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR RespSayByeMsg::RespSayByeMsg(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RespSayByeMsg_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RespSayByeMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RespSayByeMsgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RespSayByeMsgDefaultTypeInternal() {}
  union {
    RespSayByeMsg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RespSayByeMsgDefaultTypeInternal _RespSayByeMsg_default_instance_;

inline constexpr ChangeNameMsg2::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR ChangeNameMsg2::ChangeNameMsg2(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ChangeNameMsg2_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ChangeNameMsg2DefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChangeNameMsg2DefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChangeNameMsg2DefaultTypeInternal() {}
  union {
    ChangeNameMsg2 _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChangeNameMsg2DefaultTypeInternal _ChangeNameMsg2_default_instance_;

inline constexpr ChangeNameMsg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR ChangeNameMsg::ChangeNameMsg(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ChangeNameMsg_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ChangeNameMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChangeNameMsgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChangeNameMsgDefaultTypeInternal() {}
  union {
    ChangeNameMsg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChangeNameMsgDefaultTypeInternal _ChangeNameMsg_default_instance_;
}  // namespace proto
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_say_5fhello_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_say_5fhello_2eproto = nullptr;
const ::uint32_t
    TableStruct_say_5fhello_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::proto::SayHelloMsg, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::proto::SayHelloMsg, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::proto::SayHelloMsg, _impl_.name_),
        0,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::proto::SayByeMsg, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::proto::ChangeNameMsg, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::proto::ChangeNameMsg, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::proto::ChangeNameMsg, _impl_.name_),
        0,
        PROTOBUF_FIELD_OFFSET(::proto::RespSayByeMsg, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::proto::RespSayByeMsg, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::proto::RespSayByeMsg, _impl_.name_),
        0,
        PROTOBUF_FIELD_OFFSET(::proto::SayHelloMsg2, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::proto::SayHelloMsg2, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::proto::SayHelloMsg2, _impl_.name_),
        0,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::proto::SayByeMsg2, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::proto::ChangeNameMsg2, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::proto::ChangeNameMsg2, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::proto::ChangeNameMsg2, _impl_.name_),
        0,
        PROTOBUF_FIELD_OFFSET(::proto::RespSayByeMsg2, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::proto::RespSayByeMsg2, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::proto::RespSayByeMsg2, _impl_.name_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 9, -1, sizeof(::proto::SayHelloMsg)},
        {10, -1, -1, sizeof(::proto::SayByeMsg)},
        {18, 27, -1, sizeof(::proto::ChangeNameMsg)},
        {28, 37, -1, sizeof(::proto::RespSayByeMsg)},
        {38, 47, -1, sizeof(::proto::SayHelloMsg2)},
        {48, -1, -1, sizeof(::proto::SayByeMsg2)},
        {56, 65, -1, sizeof(::proto::ChangeNameMsg2)},
        {66, 75, -1, sizeof(::proto::RespSayByeMsg2)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::proto::_SayHelloMsg_default_instance_._instance,
    &::proto::_SayByeMsg_default_instance_._instance,
    &::proto::_ChangeNameMsg_default_instance_._instance,
    &::proto::_RespSayByeMsg_default_instance_._instance,
    &::proto::_SayHelloMsg2_default_instance_._instance,
    &::proto::_SayByeMsg2_default_instance_._instance,
    &::proto::_ChangeNameMsg2_default_instance_._instance,
    &::proto::_RespSayByeMsg2_default_instance_._instance,
};
const char descriptor_table_protodef_say_5fhello_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017say_hello.proto\022\005proto\"\033\n\013SayHelloMsg\022"
    "\014\n\004name\030\001 \001(\t\"\013\n\tSayByeMsg\"\035\n\rChangeName"
    "Msg\022\014\n\004name\030\001 \001(\t\"\035\n\rRespSayByeMsg\022\014\n\004na"
    "me\030\001 \001(\t\"\034\n\014SayHelloMsg2\022\014\n\004name\030\001 \001(\t\"\014"
    "\n\nSayByeMsg2\"\036\n\016ChangeNameMsg2\022\014\n\004name\030\001"
    " \001(\t\"\036\n\016RespSayByeMsg2\022\014\n\004name\030\001 \001(\tb\006pr"
    "oto3"
};
static ::absl::once_flag descriptor_table_say_5fhello_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_say_5fhello_2eproto = {
    false,
    false,
    244,
    descriptor_table_protodef_say_5fhello_2eproto,
    "say_hello.proto",
    &descriptor_table_say_5fhello_2eproto_once,
    nullptr,
    0,
    8,
    schemas,
    file_default_instances,
    TableStruct_say_5fhello_2eproto::offsets,
    file_level_enum_descriptors_say_5fhello_2eproto,
    file_level_service_descriptors_say_5fhello_2eproto,
};
namespace proto {
// ===================================================================

class SayHelloMsg::_Internal {
 public:
  using HasBits =
      decltype(std::declval<SayHelloMsg>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SayHelloMsg, _impl_._has_bits_);
};

SayHelloMsg::SayHelloMsg(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SayHelloMsg_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.SayHelloMsg)
}
PROTOBUF_NDEBUG_INLINE SayHelloMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::proto::SayHelloMsg& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

SayHelloMsg::SayHelloMsg(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SayHelloMsg& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SayHelloMsg_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SayHelloMsg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:proto.SayHelloMsg)
}
PROTOBUF_NDEBUG_INLINE SayHelloMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        name_(arena) {}

inline void SayHelloMsg::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
SayHelloMsg::~SayHelloMsg() {
  // @@protoc_insertion_point(destructor:proto.SayHelloMsg)
  SharedDtor(*this);
}
inline void SayHelloMsg::SharedDtor(MessageLite& self) {
  SayHelloMsg& this_ = static_cast<SayHelloMsg&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SayHelloMsg::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SayHelloMsg(arena);
}
constexpr auto SayHelloMsg::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SayHelloMsg),
                                            alignof(SayHelloMsg));
}
constexpr auto SayHelloMsg::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SayHelloMsg_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SayHelloMsg::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SayHelloMsg>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SayHelloMsg::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SayHelloMsg>(), &SayHelloMsg::ByteSizeLong,
              &SayHelloMsg::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SayHelloMsg, _impl_._cached_size_),
          false,
      },
      &SayHelloMsg::kDescriptorMethods,
      &descriptor_table_say_5fhello_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SayHelloMsg_class_data_ =
        SayHelloMsg::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL SayHelloMsg::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SayHelloMsg_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SayHelloMsg_class_data_.tc_table);
  return SayHelloMsg_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 30, 2>
SayHelloMsg::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SayHelloMsg, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SayHelloMsg_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::SayHelloMsg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(SayHelloMsg, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(SayHelloMsg, _impl_.name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\21\4\0\0\0\0\0\0"
    "proto.SayHelloMsg"
    "name"
  }},
};
PROTOBUF_NOINLINE void SayHelloMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.SayHelloMsg)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.name_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SayHelloMsg::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SayHelloMsg& this_ = static_cast<const SayHelloMsg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SayHelloMsg::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SayHelloMsg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:proto.SayHelloMsg)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_name().empty()) {
      const std::string& _s = this_._internal_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.SayHelloMsg.name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.SayHelloMsg)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SayHelloMsg::ByteSizeLong(const MessageLite& base) {
  const SayHelloMsg& this_ = static_cast<const SayHelloMsg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SayHelloMsg::ByteSizeLong() const {
  const SayHelloMsg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.SayHelloMsg)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string name = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_name());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SayHelloMsg::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SayHelloMsg*>(&to_msg);
  auto& from = static_cast<const SayHelloMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.SayHelloMsg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!from._internal_name().empty()) {
      _this->_internal_set_name(from._internal_name());
    } else {
      if (_this->_impl_.name_.IsDefault()) {
        _this->_internal_set_name("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SayHelloMsg::CopyFrom(const SayHelloMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.SayHelloMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SayHelloMsg::InternalSwap(SayHelloMsg* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
}

::google::protobuf::Metadata SayHelloMsg::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SayByeMsg::_Internal {
 public:
};

SayByeMsg::SayByeMsg(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, SayByeMsg_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:proto.SayByeMsg)
}
SayByeMsg::SayByeMsg(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SayByeMsg& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, SayByeMsg_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SayByeMsg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:proto.SayByeMsg)
}

inline void* PROTOBUF_NONNULL SayByeMsg::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SayByeMsg(arena);
}
constexpr auto SayByeMsg::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SayByeMsg),
                                            alignof(SayByeMsg));
}
constexpr auto SayByeMsg::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SayByeMsg_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SayByeMsg::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<SayByeMsg>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SayByeMsg::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<SayByeMsg>(), &SayByeMsg::ByteSizeLong,
              &SayByeMsg::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SayByeMsg, _impl_._cached_size_),
          false,
      },
      &SayByeMsg::kDescriptorMethods,
      &descriptor_table_say_5fhello_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SayByeMsg_class_data_ =
        SayByeMsg::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL SayByeMsg::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SayByeMsg_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SayByeMsg_class_data_.tc_table);
  return SayByeMsg_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
SayByeMsg::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SayByeMsg_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::SayByeMsg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata SayByeMsg::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ChangeNameMsg::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ChangeNameMsg>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ChangeNameMsg, _impl_._has_bits_);
};

ChangeNameMsg::ChangeNameMsg(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ChangeNameMsg_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.ChangeNameMsg)
}
PROTOBUF_NDEBUG_INLINE ChangeNameMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::proto::ChangeNameMsg& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

ChangeNameMsg::ChangeNameMsg(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ChangeNameMsg& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ChangeNameMsg_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ChangeNameMsg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:proto.ChangeNameMsg)
}
PROTOBUF_NDEBUG_INLINE ChangeNameMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        name_(arena) {}

inline void ChangeNameMsg::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ChangeNameMsg::~ChangeNameMsg() {
  // @@protoc_insertion_point(destructor:proto.ChangeNameMsg)
  SharedDtor(*this);
}
inline void ChangeNameMsg::SharedDtor(MessageLite& self) {
  ChangeNameMsg& this_ = static_cast<ChangeNameMsg&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ChangeNameMsg::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ChangeNameMsg(arena);
}
constexpr auto ChangeNameMsg::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ChangeNameMsg),
                                            alignof(ChangeNameMsg));
}
constexpr auto ChangeNameMsg::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ChangeNameMsg_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ChangeNameMsg::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ChangeNameMsg>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ChangeNameMsg::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ChangeNameMsg>(), &ChangeNameMsg::ByteSizeLong,
              &ChangeNameMsg::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ChangeNameMsg, _impl_._cached_size_),
          false,
      },
      &ChangeNameMsg::kDescriptorMethods,
      &descriptor_table_say_5fhello_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ChangeNameMsg_class_data_ =
        ChangeNameMsg::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL ChangeNameMsg::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ChangeNameMsg_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ChangeNameMsg_class_data_.tc_table);
  return ChangeNameMsg_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 32, 2>
ChangeNameMsg::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ChangeNameMsg, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ChangeNameMsg_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::ChangeNameMsg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ChangeNameMsg, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(ChangeNameMsg, _impl_.name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\23\4\0\0\0\0\0\0"
    "proto.ChangeNameMsg"
    "name"
  }},
};
PROTOBUF_NOINLINE void ChangeNameMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.ChangeNameMsg)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.name_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ChangeNameMsg::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ChangeNameMsg& this_ = static_cast<const ChangeNameMsg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ChangeNameMsg::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ChangeNameMsg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:proto.ChangeNameMsg)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_name().empty()) {
      const std::string& _s = this_._internal_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.ChangeNameMsg.name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.ChangeNameMsg)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ChangeNameMsg::ByteSizeLong(const MessageLite& base) {
  const ChangeNameMsg& this_ = static_cast<const ChangeNameMsg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ChangeNameMsg::ByteSizeLong() const {
  const ChangeNameMsg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.ChangeNameMsg)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string name = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_name());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ChangeNameMsg::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ChangeNameMsg*>(&to_msg);
  auto& from = static_cast<const ChangeNameMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.ChangeNameMsg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!from._internal_name().empty()) {
      _this->_internal_set_name(from._internal_name());
    } else {
      if (_this->_impl_.name_.IsDefault()) {
        _this->_internal_set_name("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ChangeNameMsg::CopyFrom(const ChangeNameMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.ChangeNameMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ChangeNameMsg::InternalSwap(ChangeNameMsg* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
}

::google::protobuf::Metadata ChangeNameMsg::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RespSayByeMsg::_Internal {
 public:
  using HasBits =
      decltype(std::declval<RespSayByeMsg>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RespSayByeMsg, _impl_._has_bits_);
};

RespSayByeMsg::RespSayByeMsg(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RespSayByeMsg_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.RespSayByeMsg)
}
PROTOBUF_NDEBUG_INLINE RespSayByeMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::proto::RespSayByeMsg& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

RespSayByeMsg::RespSayByeMsg(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RespSayByeMsg& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RespSayByeMsg_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RespSayByeMsg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:proto.RespSayByeMsg)
}
PROTOBUF_NDEBUG_INLINE RespSayByeMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        name_(arena) {}

inline void RespSayByeMsg::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RespSayByeMsg::~RespSayByeMsg() {
  // @@protoc_insertion_point(destructor:proto.RespSayByeMsg)
  SharedDtor(*this);
}
inline void RespSayByeMsg::SharedDtor(MessageLite& self) {
  RespSayByeMsg& this_ = static_cast<RespSayByeMsg&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RespSayByeMsg::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RespSayByeMsg(arena);
}
constexpr auto RespSayByeMsg::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RespSayByeMsg),
                                            alignof(RespSayByeMsg));
}
constexpr auto RespSayByeMsg::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RespSayByeMsg_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RespSayByeMsg::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RespSayByeMsg>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RespSayByeMsg::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RespSayByeMsg>(), &RespSayByeMsg::ByteSizeLong,
              &RespSayByeMsg::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RespSayByeMsg, _impl_._cached_size_),
          false,
      },
      &RespSayByeMsg::kDescriptorMethods,
      &descriptor_table_say_5fhello_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RespSayByeMsg_class_data_ =
        RespSayByeMsg::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL RespSayByeMsg::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RespSayByeMsg_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RespSayByeMsg_class_data_.tc_table);
  return RespSayByeMsg_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 32, 2>
RespSayByeMsg::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RespSayByeMsg, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RespSayByeMsg_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::RespSayByeMsg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(RespSayByeMsg, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(RespSayByeMsg, _impl_.name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\23\4\0\0\0\0\0\0"
    "proto.RespSayByeMsg"
    "name"
  }},
};
PROTOBUF_NOINLINE void RespSayByeMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.RespSayByeMsg)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.name_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RespSayByeMsg::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RespSayByeMsg& this_ = static_cast<const RespSayByeMsg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RespSayByeMsg::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RespSayByeMsg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:proto.RespSayByeMsg)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_name().empty()) {
      const std::string& _s = this_._internal_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.RespSayByeMsg.name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.RespSayByeMsg)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RespSayByeMsg::ByteSizeLong(const MessageLite& base) {
  const RespSayByeMsg& this_ = static_cast<const RespSayByeMsg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RespSayByeMsg::ByteSizeLong() const {
  const RespSayByeMsg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.RespSayByeMsg)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string name = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_name());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RespSayByeMsg::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RespSayByeMsg*>(&to_msg);
  auto& from = static_cast<const RespSayByeMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.RespSayByeMsg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!from._internal_name().empty()) {
      _this->_internal_set_name(from._internal_name());
    } else {
      if (_this->_impl_.name_.IsDefault()) {
        _this->_internal_set_name("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RespSayByeMsg::CopyFrom(const RespSayByeMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.RespSayByeMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RespSayByeMsg::InternalSwap(RespSayByeMsg* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
}

::google::protobuf::Metadata RespSayByeMsg::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SayHelloMsg2::_Internal {
 public:
  using HasBits =
      decltype(std::declval<SayHelloMsg2>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SayHelloMsg2, _impl_._has_bits_);
};

SayHelloMsg2::SayHelloMsg2(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SayHelloMsg2_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.SayHelloMsg2)
}
PROTOBUF_NDEBUG_INLINE SayHelloMsg2::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::proto::SayHelloMsg2& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

SayHelloMsg2::SayHelloMsg2(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SayHelloMsg2& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SayHelloMsg2_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SayHelloMsg2* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:proto.SayHelloMsg2)
}
PROTOBUF_NDEBUG_INLINE SayHelloMsg2::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        name_(arena) {}

inline void SayHelloMsg2::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
SayHelloMsg2::~SayHelloMsg2() {
  // @@protoc_insertion_point(destructor:proto.SayHelloMsg2)
  SharedDtor(*this);
}
inline void SayHelloMsg2::SharedDtor(MessageLite& self) {
  SayHelloMsg2& this_ = static_cast<SayHelloMsg2&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SayHelloMsg2::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SayHelloMsg2(arena);
}
constexpr auto SayHelloMsg2::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SayHelloMsg2),
                                            alignof(SayHelloMsg2));
}
constexpr auto SayHelloMsg2::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SayHelloMsg2_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SayHelloMsg2::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SayHelloMsg2>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SayHelloMsg2::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SayHelloMsg2>(), &SayHelloMsg2::ByteSizeLong,
              &SayHelloMsg2::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SayHelloMsg2, _impl_._cached_size_),
          false,
      },
      &SayHelloMsg2::kDescriptorMethods,
      &descriptor_table_say_5fhello_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SayHelloMsg2_class_data_ =
        SayHelloMsg2::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL SayHelloMsg2::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SayHelloMsg2_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SayHelloMsg2_class_data_.tc_table);
  return SayHelloMsg2_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 31, 2>
SayHelloMsg2::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SayHelloMsg2, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SayHelloMsg2_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::SayHelloMsg2>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(SayHelloMsg2, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(SayHelloMsg2, _impl_.name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\4\0\0\0\0\0\0"
    "proto.SayHelloMsg2"
    "name"
  }},
};
PROTOBUF_NOINLINE void SayHelloMsg2::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.SayHelloMsg2)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.name_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SayHelloMsg2::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SayHelloMsg2& this_ = static_cast<const SayHelloMsg2&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SayHelloMsg2::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SayHelloMsg2& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:proto.SayHelloMsg2)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_name().empty()) {
      const std::string& _s = this_._internal_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.SayHelloMsg2.name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.SayHelloMsg2)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SayHelloMsg2::ByteSizeLong(const MessageLite& base) {
  const SayHelloMsg2& this_ = static_cast<const SayHelloMsg2&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SayHelloMsg2::ByteSizeLong() const {
  const SayHelloMsg2& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.SayHelloMsg2)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string name = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_name());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SayHelloMsg2::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SayHelloMsg2*>(&to_msg);
  auto& from = static_cast<const SayHelloMsg2&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.SayHelloMsg2)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!from._internal_name().empty()) {
      _this->_internal_set_name(from._internal_name());
    } else {
      if (_this->_impl_.name_.IsDefault()) {
        _this->_internal_set_name("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SayHelloMsg2::CopyFrom(const SayHelloMsg2& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.SayHelloMsg2)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SayHelloMsg2::InternalSwap(SayHelloMsg2* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
}

::google::protobuf::Metadata SayHelloMsg2::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SayByeMsg2::_Internal {
 public:
};

SayByeMsg2::SayByeMsg2(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, SayByeMsg2_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:proto.SayByeMsg2)
}
SayByeMsg2::SayByeMsg2(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SayByeMsg2& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, SayByeMsg2_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SayByeMsg2* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:proto.SayByeMsg2)
}

inline void* PROTOBUF_NONNULL SayByeMsg2::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SayByeMsg2(arena);
}
constexpr auto SayByeMsg2::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SayByeMsg2),
                                            alignof(SayByeMsg2));
}
constexpr auto SayByeMsg2::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SayByeMsg2_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SayByeMsg2::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<SayByeMsg2>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SayByeMsg2::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<SayByeMsg2>(), &SayByeMsg2::ByteSizeLong,
              &SayByeMsg2::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SayByeMsg2, _impl_._cached_size_),
          false,
      },
      &SayByeMsg2::kDescriptorMethods,
      &descriptor_table_say_5fhello_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SayByeMsg2_class_data_ =
        SayByeMsg2::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL SayByeMsg2::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SayByeMsg2_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SayByeMsg2_class_data_.tc_table);
  return SayByeMsg2_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
SayByeMsg2::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SayByeMsg2_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::SayByeMsg2>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata SayByeMsg2::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ChangeNameMsg2::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ChangeNameMsg2>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ChangeNameMsg2, _impl_._has_bits_);
};

ChangeNameMsg2::ChangeNameMsg2(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ChangeNameMsg2_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.ChangeNameMsg2)
}
PROTOBUF_NDEBUG_INLINE ChangeNameMsg2::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::proto::ChangeNameMsg2& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

ChangeNameMsg2::ChangeNameMsg2(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ChangeNameMsg2& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ChangeNameMsg2_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ChangeNameMsg2* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:proto.ChangeNameMsg2)
}
PROTOBUF_NDEBUG_INLINE ChangeNameMsg2::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        name_(arena) {}

inline void ChangeNameMsg2::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ChangeNameMsg2::~ChangeNameMsg2() {
  // @@protoc_insertion_point(destructor:proto.ChangeNameMsg2)
  SharedDtor(*this);
}
inline void ChangeNameMsg2::SharedDtor(MessageLite& self) {
  ChangeNameMsg2& this_ = static_cast<ChangeNameMsg2&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ChangeNameMsg2::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ChangeNameMsg2(arena);
}
constexpr auto ChangeNameMsg2::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ChangeNameMsg2),
                                            alignof(ChangeNameMsg2));
}
constexpr auto ChangeNameMsg2::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ChangeNameMsg2_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ChangeNameMsg2::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ChangeNameMsg2>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ChangeNameMsg2::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ChangeNameMsg2>(), &ChangeNameMsg2::ByteSizeLong,
              &ChangeNameMsg2::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ChangeNameMsg2, _impl_._cached_size_),
          false,
      },
      &ChangeNameMsg2::kDescriptorMethods,
      &descriptor_table_say_5fhello_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ChangeNameMsg2_class_data_ =
        ChangeNameMsg2::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL ChangeNameMsg2::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ChangeNameMsg2_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ChangeNameMsg2_class_data_.tc_table);
  return ChangeNameMsg2_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 33, 2>
ChangeNameMsg2::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ChangeNameMsg2, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ChangeNameMsg2_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::ChangeNameMsg2>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ChangeNameMsg2, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(ChangeNameMsg2, _impl_.name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\24\4\0\0\0\0\0\0"
    "proto.ChangeNameMsg2"
    "name"
  }},
};
PROTOBUF_NOINLINE void ChangeNameMsg2::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.ChangeNameMsg2)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.name_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ChangeNameMsg2::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ChangeNameMsg2& this_ = static_cast<const ChangeNameMsg2&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ChangeNameMsg2::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ChangeNameMsg2& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:proto.ChangeNameMsg2)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_name().empty()) {
      const std::string& _s = this_._internal_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.ChangeNameMsg2.name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.ChangeNameMsg2)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ChangeNameMsg2::ByteSizeLong(const MessageLite& base) {
  const ChangeNameMsg2& this_ = static_cast<const ChangeNameMsg2&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ChangeNameMsg2::ByteSizeLong() const {
  const ChangeNameMsg2& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.ChangeNameMsg2)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string name = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_name());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ChangeNameMsg2::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ChangeNameMsg2*>(&to_msg);
  auto& from = static_cast<const ChangeNameMsg2&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.ChangeNameMsg2)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!from._internal_name().empty()) {
      _this->_internal_set_name(from._internal_name());
    } else {
      if (_this->_impl_.name_.IsDefault()) {
        _this->_internal_set_name("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ChangeNameMsg2::CopyFrom(const ChangeNameMsg2& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.ChangeNameMsg2)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ChangeNameMsg2::InternalSwap(ChangeNameMsg2* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
}

::google::protobuf::Metadata ChangeNameMsg2::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RespSayByeMsg2::_Internal {
 public:
  using HasBits =
      decltype(std::declval<RespSayByeMsg2>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RespSayByeMsg2, _impl_._has_bits_);
};

RespSayByeMsg2::RespSayByeMsg2(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RespSayByeMsg2_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.RespSayByeMsg2)
}
PROTOBUF_NDEBUG_INLINE RespSayByeMsg2::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::proto::RespSayByeMsg2& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

RespSayByeMsg2::RespSayByeMsg2(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RespSayByeMsg2& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RespSayByeMsg2_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RespSayByeMsg2* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:proto.RespSayByeMsg2)
}
PROTOBUF_NDEBUG_INLINE RespSayByeMsg2::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        name_(arena) {}

inline void RespSayByeMsg2::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RespSayByeMsg2::~RespSayByeMsg2() {
  // @@protoc_insertion_point(destructor:proto.RespSayByeMsg2)
  SharedDtor(*this);
}
inline void RespSayByeMsg2::SharedDtor(MessageLite& self) {
  RespSayByeMsg2& this_ = static_cast<RespSayByeMsg2&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RespSayByeMsg2::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RespSayByeMsg2(arena);
}
constexpr auto RespSayByeMsg2::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RespSayByeMsg2),
                                            alignof(RespSayByeMsg2));
}
constexpr auto RespSayByeMsg2::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RespSayByeMsg2_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RespSayByeMsg2::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RespSayByeMsg2>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RespSayByeMsg2::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RespSayByeMsg2>(), &RespSayByeMsg2::ByteSizeLong,
              &RespSayByeMsg2::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RespSayByeMsg2, _impl_._cached_size_),
          false,
      },
      &RespSayByeMsg2::kDescriptorMethods,
      &descriptor_table_say_5fhello_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RespSayByeMsg2_class_data_ =
        RespSayByeMsg2::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL RespSayByeMsg2::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RespSayByeMsg2_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RespSayByeMsg2_class_data_.tc_table);
  return RespSayByeMsg2_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 33, 2>
RespSayByeMsg2::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RespSayByeMsg2, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RespSayByeMsg2_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::RespSayByeMsg2>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(RespSayByeMsg2, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(RespSayByeMsg2, _impl_.name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\24\4\0\0\0\0\0\0"
    "proto.RespSayByeMsg2"
    "name"
  }},
};
PROTOBUF_NOINLINE void RespSayByeMsg2::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.RespSayByeMsg2)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.name_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RespSayByeMsg2::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RespSayByeMsg2& this_ = static_cast<const RespSayByeMsg2&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RespSayByeMsg2::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RespSayByeMsg2& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:proto.RespSayByeMsg2)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_name().empty()) {
      const std::string& _s = this_._internal_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.RespSayByeMsg2.name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.RespSayByeMsg2)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RespSayByeMsg2::ByteSizeLong(const MessageLite& base) {
  const RespSayByeMsg2& this_ = static_cast<const RespSayByeMsg2&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RespSayByeMsg2::ByteSizeLong() const {
  const RespSayByeMsg2& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.RespSayByeMsg2)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string name = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_name());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RespSayByeMsg2::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RespSayByeMsg2*>(&to_msg);
  auto& from = static_cast<const RespSayByeMsg2&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.RespSayByeMsg2)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!from._internal_name().empty()) {
      _this->_internal_set_name(from._internal_name());
    } else {
      if (_this->_impl_.name_.IsDefault()) {
        _this->_internal_set_name("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RespSayByeMsg2::CopyFrom(const RespSayByeMsg2& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.RespSayByeMsg2)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RespSayByeMsg2::InternalSwap(RespSayByeMsg2* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
}

::google::protobuf::Metadata RespSayByeMsg2::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_say_5fhello_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
