// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: p2p_client.proto
// Protobuf C++ Version: 6.30.2

#ifndef p2p_5fclient_2eproto_2epb_2eh
#define p2p_5fclient_2eproto_2epb_2eh

#include <limits>
#include "mqas/macro.h"
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6030002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "common.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_p2p_5fclient_2eproto MQAS_EXTERN

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct MQAS_EXTERN TableStruct_p2p_5fclient_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
MQAS_EXTERN extern const ::google::protobuf::internal::DescriptorTable descriptor_table_p2p_5fclient_2eproto;
}  // extern "C"
namespace mqas {
namespace tools {
namespace proto {
namespace p2p_client {
enum RetCode : int;
MQAS_EXTERN extern const uint32_t RetCode_internal_data_[];
class RequestDirectConnect;
struct RequestDirectConnectDefaultTypeInternal;
MQAS_EXTERN extern RequestDirectConnectDefaultTypeInternal _RequestDirectConnect_default_instance_;
MQAS_EXTERN extern const ::google::protobuf::internal::ClassDataFull RequestDirectConnect_class_data_;
class RequestDirectQuit;
struct RequestDirectQuitDefaultTypeInternal;
MQAS_EXTERN extern RequestDirectQuitDefaultTypeInternal _RequestDirectQuit_default_instance_;
MQAS_EXTERN extern const ::google::protobuf::internal::ClassDataFull RequestDirectQuit_class_data_;
class RespondDirectConnect;
struct RespondDirectConnectDefaultTypeInternal;
MQAS_EXTERN extern RespondDirectConnectDefaultTypeInternal _RespondDirectConnect_default_instance_;
MQAS_EXTERN extern const ::google::protobuf::internal::ClassDataFull RespondDirectConnect_class_data_;
class RespondDirectQuit;
struct RespondDirectQuitDefaultTypeInternal;
MQAS_EXTERN extern RespondDirectQuitDefaultTypeInternal _RespondDirectQuit_default_instance_;
MQAS_EXTERN extern const ::google::protobuf::internal::ClassDataFull RespondDirectQuit_class_data_;
}  // namespace p2p_client
}  // namespace proto
}  // namespace tools
}  // namespace mqas
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::mqas::tools::proto::p2p_client::RetCode_internal_data_>
    internal::EnumTraitsImpl::value<::mqas::tools::proto::p2p_client::RetCode>;
}  // namespace protobuf
}  // namespace google

namespace mqas {
namespace tools {
namespace proto {
namespace p2p_client {
enum RetCode : int {
  ok = 0,
  wrong_token = 1,
  already_connected = 2,
  token_not_found = 3,
  unknown_error = 4,
  not_submit_token = 5,
  refused_by_peer = 6,
  RetCode_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  RetCode_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

MQAS_EXTERN extern const uint32_t RetCode_internal_data_[];
inline constexpr RetCode RetCode_MIN =
    static_cast<RetCode>(0);
inline constexpr RetCode RetCode_MAX =
    static_cast<RetCode>(6);
inline bool RetCode_IsValid(int value) {
  return 0 <= value && value <= 6;
}
inline constexpr int RetCode_ARRAYSIZE = 6 + 1;
MQAS_EXTERN const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL RetCode_descriptor();
template <typename T>
const std::string& RetCode_Name(T value) {
  static_assert(std::is_same<T, RetCode>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to RetCode_Name().");
  return RetCode_Name(static_cast<RetCode>(value));
}
template <>
inline const std::string& RetCode_Name(RetCode value) {
  return ::google::protobuf::internal::NameOfDenseEnum<RetCode_descriptor, 0, 6>(
      static_cast<int>(value));
}
inline bool RetCode_Parse(
    absl::string_view name, RetCode* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<RetCode>(RetCode_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class MQAS_EXTERN RespondDirectQuit final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mqas.tools.proto.p2p_client.RespondDirectQuit) */ {
 public:
  inline RespondDirectQuit() : RespondDirectQuit(nullptr) {}
  ~RespondDirectQuit() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RespondDirectQuit* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RespondDirectQuit));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RespondDirectQuit(::google::protobuf::internal::ConstantInitialized);

  inline RespondDirectQuit(const RespondDirectQuit& from) : RespondDirectQuit(nullptr, from) {}
  inline RespondDirectQuit(RespondDirectQuit&& from) noexcept
      : RespondDirectQuit(nullptr, std::move(from)) {}
  inline RespondDirectQuit& operator=(const RespondDirectQuit& from) {
    CopyFrom(from);
    return *this;
  }
  inline RespondDirectQuit& operator=(RespondDirectQuit&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RespondDirectQuit& default_instance() {
    return *reinterpret_cast<const RespondDirectQuit*>(
        &_RespondDirectQuit_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(RespondDirectQuit& a, RespondDirectQuit& b) { a.Swap(&b); }
  inline void Swap(RespondDirectQuit* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RespondDirectQuit* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RespondDirectQuit* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RespondDirectQuit>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RespondDirectQuit& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RespondDirectQuit& from) { RespondDirectQuit::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RespondDirectQuit* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mqas.tools.proto.p2p_client.RespondDirectQuit"; }

 protected:
  explicit RespondDirectQuit(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RespondDirectQuit(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RespondDirectQuit& from);
  RespondDirectQuit(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RespondDirectQuit&& from) noexcept
      : RespondDirectQuit(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCodeFieldNumber = 1,
  };
  // .mqas.tools.proto.p2p_client.RetCode code = 1;
  void clear_code() ;
  ::mqas::tools::proto::p2p_client::RetCode code() const;
  void set_code(::mqas::tools::proto::p2p_client::RetCode value);

  private:
  ::mqas::tools::proto::p2p_client::RetCode _internal_code() const;
  void _internal_set_code(::mqas::tools::proto::p2p_client::RetCode value);

  public:
  // @@protoc_insertion_point(class_scope:mqas.tools.proto.p2p_client.RespondDirectQuit)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RespondDirectQuit& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    int code_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_p2p_5fclient_2eproto;
};

MQAS_EXTERN extern const ::google::protobuf::internal::ClassDataFull RespondDirectQuit_class_data_;
// -------------------------------------------------------------------

class MQAS_EXTERN RespondDirectConnect final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mqas.tools.proto.p2p_client.RespondDirectConnect) */ {
 public:
  inline RespondDirectConnect() : RespondDirectConnect(nullptr) {}
  ~RespondDirectConnect() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RespondDirectConnect* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RespondDirectConnect));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RespondDirectConnect(::google::protobuf::internal::ConstantInitialized);

  inline RespondDirectConnect(const RespondDirectConnect& from) : RespondDirectConnect(nullptr, from) {}
  inline RespondDirectConnect(RespondDirectConnect&& from) noexcept
      : RespondDirectConnect(nullptr, std::move(from)) {}
  inline RespondDirectConnect& operator=(const RespondDirectConnect& from) {
    CopyFrom(from);
    return *this;
  }
  inline RespondDirectConnect& operator=(RespondDirectConnect&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RespondDirectConnect& default_instance() {
    return *reinterpret_cast<const RespondDirectConnect*>(
        &_RespondDirectConnect_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(RespondDirectConnect& a, RespondDirectConnect& b) { a.Swap(&b); }
  inline void Swap(RespondDirectConnect* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RespondDirectConnect* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RespondDirectConnect* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RespondDirectConnect>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RespondDirectConnect& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RespondDirectConnect& from) { RespondDirectConnect::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RespondDirectConnect* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mqas.tools.proto.p2p_client.RespondDirectConnect"; }

 protected:
  explicit RespondDirectConnect(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RespondDirectConnect(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RespondDirectConnect& from);
  RespondDirectConnect(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RespondDirectConnect&& from) noexcept
      : RespondDirectConnect(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 2,
    kCodeFieldNumber = 1,
  };
  // string name = 2;
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // .mqas.tools.proto.p2p_client.RetCode code = 1;
  void clear_code() ;
  ::mqas::tools::proto::p2p_client::RetCode code() const;
  void set_code(::mqas::tools::proto::p2p_client::RetCode value);

  private:
  ::mqas::tools::proto::p2p_client::RetCode _internal_code() const;
  void _internal_set_code(::mqas::tools::proto::p2p_client::RetCode value);

  public:
  // @@protoc_insertion_point(class_scope:mqas.tools.proto.p2p_client.RespondDirectConnect)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 61,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RespondDirectConnect& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    int code_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_p2p_5fclient_2eproto;
};

MQAS_EXTERN extern const ::google::protobuf::internal::ClassDataFull RespondDirectConnect_class_data_;
// -------------------------------------------------------------------

class MQAS_EXTERN RequestDirectQuit final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mqas.tools.proto.p2p_client.RequestDirectQuit) */ {
 public:
  inline RequestDirectQuit() : RequestDirectQuit(nullptr) {}
  ~RequestDirectQuit() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RequestDirectQuit* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RequestDirectQuit));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RequestDirectQuit(::google::protobuf::internal::ConstantInitialized);

  inline RequestDirectQuit(const RequestDirectQuit& from) : RequestDirectQuit(nullptr, from) {}
  inline RequestDirectQuit(RequestDirectQuit&& from) noexcept
      : RequestDirectQuit(nullptr, std::move(from)) {}
  inline RequestDirectQuit& operator=(const RequestDirectQuit& from) {
    CopyFrom(from);
    return *this;
  }
  inline RequestDirectQuit& operator=(RequestDirectQuit&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RequestDirectQuit& default_instance() {
    return *reinterpret_cast<const RequestDirectQuit*>(
        &_RequestDirectQuit_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(RequestDirectQuit& a, RequestDirectQuit& b) { a.Swap(&b); }
  inline void Swap(RequestDirectQuit* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RequestDirectQuit* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RequestDirectQuit* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RequestDirectQuit>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RequestDirectQuit& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RequestDirectQuit& from) { RequestDirectQuit::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RequestDirectQuit* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mqas.tools.proto.p2p_client.RequestDirectQuit"; }

 protected:
  explicit RequestDirectQuit(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RequestDirectQuit(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RequestDirectQuit& from);
  RequestDirectQuit(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RequestDirectQuit&& from) noexcept
      : RequestDirectQuit(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kReasonFieldNumber = 1,
  };
  // optional string reason = 1;
  bool has_reason() const;
  void clear_reason() ;
  const std::string& reason() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_reason(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_reason();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_reason();
  void set_allocated_reason(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_reason() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_reason(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_reason();

  public:
  // @@protoc_insertion_point(class_scope:mqas.tools.proto.p2p_client.RequestDirectQuit)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 60,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RequestDirectQuit& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr reason_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_p2p_5fclient_2eproto;
};

MQAS_EXTERN extern const ::google::protobuf::internal::ClassDataFull RequestDirectQuit_class_data_;
// -------------------------------------------------------------------

class MQAS_EXTERN RequestDirectConnect final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mqas.tools.proto.p2p_client.RequestDirectConnect) */ {
 public:
  inline RequestDirectConnect() : RequestDirectConnect(nullptr) {}
  ~RequestDirectConnect() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RequestDirectConnect* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RequestDirectConnect));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RequestDirectConnect(::google::protobuf::internal::ConstantInitialized);

  inline RequestDirectConnect(const RequestDirectConnect& from) : RequestDirectConnect(nullptr, from) {}
  inline RequestDirectConnect(RequestDirectConnect&& from) noexcept
      : RequestDirectConnect(nullptr, std::move(from)) {}
  inline RequestDirectConnect& operator=(const RequestDirectConnect& from) {
    CopyFrom(from);
    return *this;
  }
  inline RequestDirectConnect& operator=(RequestDirectConnect&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RequestDirectConnect& default_instance() {
    return *reinterpret_cast<const RequestDirectConnect*>(
        &_RequestDirectConnect_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(RequestDirectConnect& a, RequestDirectConnect& b) { a.Swap(&b); }
  inline void Swap(RequestDirectConnect* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RequestDirectConnect* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RequestDirectConnect* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RequestDirectConnect>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RequestDirectConnect& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RequestDirectConnect& from) { RequestDirectConnect::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RequestDirectConnect* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mqas.tools.proto.p2p_client.RequestDirectConnect"; }

 protected:
  explicit RequestDirectConnect(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RequestDirectConnect(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RequestDirectConnect& from);
  RequestDirectConnect(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RequestDirectConnect&& from) noexcept
      : RequestDirectConnect(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 2,
    kTokenFieldNumber = 1,
  };
  // string name = 2;
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // .mqas.tools.proto.common.UUID token = 1;
  bool has_token() const;
  void clear_token() ;
  const ::mqas::tools::proto::common::UUID& token() const;
  [[nodiscard]] ::mqas::tools::proto::common::UUID* PROTOBUF_NULLABLE release_token();
  ::mqas::tools::proto::common::UUID* PROTOBUF_NONNULL mutable_token();
  void set_allocated_token(::mqas::tools::proto::common::UUID* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_token(::mqas::tools::proto::common::UUID* PROTOBUF_NULLABLE value);
  ::mqas::tools::proto::common::UUID* PROTOBUF_NULLABLE unsafe_arena_release_token();

  private:
  const ::mqas::tools::proto::common::UUID& _internal_token() const;
  ::mqas::tools::proto::common::UUID* PROTOBUF_NONNULL _internal_mutable_token();

  public:
  // @@protoc_insertion_point(class_scope:mqas.tools.proto.p2p_client.RequestDirectConnect)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 61,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RequestDirectConnect& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::mqas::tools::proto::common::UUID* PROTOBUF_NULLABLE token_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_p2p_5fclient_2eproto;
};

MQAS_EXTERN extern const ::google::protobuf::internal::ClassDataFull RequestDirectConnect_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RequestDirectConnect

// .mqas.tools.proto.common.UUID token = 1;
inline bool RequestDirectConnect::has_token() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.token_ != nullptr);
  return value;
}
inline const ::mqas::tools::proto::common::UUID& RequestDirectConnect::_internal_token() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::mqas::tools::proto::common::UUID* p = _impl_.token_;
  return p != nullptr ? *p : reinterpret_cast<const ::mqas::tools::proto::common::UUID&>(::mqas::tools::proto::common::_UUID_default_instance_);
}
inline const ::mqas::tools::proto::common::UUID& RequestDirectConnect::token() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mqas.tools.proto.p2p_client.RequestDirectConnect.token)
  return _internal_token();
}
inline void RequestDirectConnect::unsafe_arena_set_allocated_token(
    ::mqas::tools::proto::common::UUID* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.token_);
  }
  _impl_.token_ = reinterpret_cast<::mqas::tools::proto::common::UUID*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mqas.tools.proto.p2p_client.RequestDirectConnect.token)
}
inline ::mqas::tools::proto::common::UUID* PROTOBUF_NULLABLE RequestDirectConnect::release_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::mqas::tools::proto::common::UUID* released = _impl_.token_;
  _impl_.token_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::mqas::tools::proto::common::UUID* PROTOBUF_NULLABLE RequestDirectConnect::unsafe_arena_release_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mqas.tools.proto.p2p_client.RequestDirectConnect.token)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::mqas::tools::proto::common::UUID* temp = _impl_.token_;
  _impl_.token_ = nullptr;
  return temp;
}
inline ::mqas::tools::proto::common::UUID* PROTOBUF_NONNULL RequestDirectConnect::_internal_mutable_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.token_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::mqas::tools::proto::common::UUID>(GetArena());
    _impl_.token_ = reinterpret_cast<::mqas::tools::proto::common::UUID*>(p);
  }
  return _impl_.token_;
}
inline ::mqas::tools::proto::common::UUID* PROTOBUF_NONNULL RequestDirectConnect::mutable_token()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::mqas::tools::proto::common::UUID* _msg = _internal_mutable_token();
  // @@protoc_insertion_point(field_mutable:mqas.tools.proto.p2p_client.RequestDirectConnect.token)
  return _msg;
}
inline void RequestDirectConnect::set_allocated_token(::mqas::tools::proto::common::UUID* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.token_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.token_ = reinterpret_cast<::mqas::tools::proto::common::UUID*>(value);
  // @@protoc_insertion_point(field_set_allocated:mqas.tools.proto.p2p_client.RequestDirectConnect.token)
}

// string name = 2;
inline void RequestDirectConnect::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& RequestDirectConnect::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mqas.tools.proto.p2p_client.RequestDirectConnect.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RequestDirectConnect::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mqas.tools.proto.p2p_client.RequestDirectConnect.name)
}
inline std::string* PROTOBUF_NONNULL RequestDirectConnect::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:mqas.tools.proto.p2p_client.RequestDirectConnect.name)
  return _s;
}
inline const std::string& RequestDirectConnect::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void RequestDirectConnect::_internal_set_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL RequestDirectConnect::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.name_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE RequestDirectConnect::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mqas.tools.proto.p2p_client.RequestDirectConnect.name)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void RequestDirectConnect::set_allocated_name(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mqas.tools.proto.p2p_client.RequestDirectConnect.name)
}

// -------------------------------------------------------------------

// RespondDirectConnect

// .mqas.tools.proto.p2p_client.RetCode code = 1;
inline void RespondDirectConnect::clear_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::mqas::tools::proto::p2p_client::RetCode RespondDirectConnect::code() const {
  // @@protoc_insertion_point(field_get:mqas.tools.proto.p2p_client.RespondDirectConnect.code)
  return _internal_code();
}
inline void RespondDirectConnect::set_code(::mqas::tools::proto::p2p_client::RetCode value) {
  _internal_set_code(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:mqas.tools.proto.p2p_client.RespondDirectConnect.code)
}
inline ::mqas::tools::proto::p2p_client::RetCode RespondDirectConnect::_internal_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::mqas::tools::proto::p2p_client::RetCode>(_impl_.code_);
}
inline void RespondDirectConnect::_internal_set_code(::mqas::tools::proto::p2p_client::RetCode value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_ = value;
}

// string name = 2;
inline void RespondDirectConnect::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& RespondDirectConnect::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mqas.tools.proto.p2p_client.RespondDirectConnect.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RespondDirectConnect::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mqas.tools.proto.p2p_client.RespondDirectConnect.name)
}
inline std::string* PROTOBUF_NONNULL RespondDirectConnect::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:mqas.tools.proto.p2p_client.RespondDirectConnect.name)
  return _s;
}
inline const std::string& RespondDirectConnect::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void RespondDirectConnect::_internal_set_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL RespondDirectConnect::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.name_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE RespondDirectConnect::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mqas.tools.proto.p2p_client.RespondDirectConnect.name)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void RespondDirectConnect::set_allocated_name(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mqas.tools.proto.p2p_client.RespondDirectConnect.name)
}

// -------------------------------------------------------------------

// RequestDirectQuit

// optional string reason = 1;
inline bool RequestDirectQuit::has_reason() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void RequestDirectQuit::clear_reason() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reason_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& RequestDirectQuit::reason() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mqas.tools.proto.p2p_client.RequestDirectQuit.reason)
  return _internal_reason();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RequestDirectQuit::set_reason(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.reason_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mqas.tools.proto.p2p_client.RequestDirectQuit.reason)
}
inline std::string* PROTOBUF_NONNULL RequestDirectQuit::mutable_reason()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_reason();
  // @@protoc_insertion_point(field_mutable:mqas.tools.proto.p2p_client.RequestDirectQuit.reason)
  return _s;
}
inline const std::string& RequestDirectQuit::_internal_reason() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.reason_.Get();
}
inline void RequestDirectQuit::_internal_set_reason(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.reason_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL RequestDirectQuit::_internal_mutable_reason() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.reason_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE RequestDirectQuit::release_reason() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mqas.tools.proto.p2p_client.RequestDirectQuit.reason)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.reason_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.reason_.Set("", GetArena());
  }
  return released;
}
inline void RequestDirectQuit::set_allocated_reason(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.reason_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.reason_.IsDefault()) {
    _impl_.reason_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mqas.tools.proto.p2p_client.RequestDirectQuit.reason)
}

// -------------------------------------------------------------------

// RespondDirectQuit

// .mqas.tools.proto.p2p_client.RetCode code = 1;
inline void RespondDirectQuit::clear_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::mqas::tools::proto::p2p_client::RetCode RespondDirectQuit::code() const {
  // @@protoc_insertion_point(field_get:mqas.tools.proto.p2p_client.RespondDirectQuit.code)
  return _internal_code();
}
inline void RespondDirectQuit::set_code(::mqas::tools::proto::p2p_client::RetCode value) {
  _internal_set_code(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:mqas.tools.proto.p2p_client.RespondDirectQuit.code)
}
inline ::mqas::tools::proto::p2p_client::RetCode RespondDirectQuit::_internal_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::mqas::tools::proto::p2p_client::RetCode>(_impl_.code_);
}
inline void RespondDirectQuit::_internal_set_code(::mqas::tools::proto::p2p_client::RetCode value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace p2p_client
}  // namespace proto
}  // namespace tools
}  // namespace mqas


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::mqas::tools::proto::p2p_client::RetCode> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::mqas::tools::proto::p2p_client::RetCode>() {
  return ::mqas::tools::proto::p2p_client::RetCode_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // p2p_5fclient_2eproto_2epb_2eh
