// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: send_file.proto
// Protobuf C++ Version: 6.30.2

#ifndef send_5ffile_2eproto_2epb_2eh
#define send_5ffile_2eproto_2epb_2eh

#include <limits>
#include "mqas/macro.h"
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6030002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_send_5ffile_2eproto MQAS_EXTERN

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct MQAS_EXTERN TableStruct_send_5ffile_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
MQAS_EXTERN extern const ::google::protobuf::internal::DescriptorTable descriptor_table_send_5ffile_2eproto;
}  // extern "C"
namespace mqas {
namespace tools {
namespace proto {
enum ReqSendFileRet_Code : int;
MQAS_EXTERN extern const uint32_t ReqSendFileRet_Code_internal_data_[];
class ReqSendFile;
struct ReqSendFileDefaultTypeInternal;
MQAS_EXTERN extern ReqSendFileDefaultTypeInternal _ReqSendFile_default_instance_;
MQAS_EXTERN extern const ::google::protobuf::internal::ClassDataFull ReqSendFile_class_data_;
class ReqSendFileRet;
struct ReqSendFileRetDefaultTypeInternal;
MQAS_EXTERN extern ReqSendFileRetDefaultTypeInternal _ReqSendFileRet_default_instance_;
MQAS_EXTERN extern const ::google::protobuf::internal::ClassDataFull ReqSendFileRet_class_data_;
class SendFileEnd;
struct SendFileEndDefaultTypeInternal;
MQAS_EXTERN extern SendFileEndDefaultTypeInternal _SendFileEnd_default_instance_;
MQAS_EXTERN extern const ::google::protobuf::internal::ClassDataFull SendFileEnd_class_data_;
}  // namespace proto
}  // namespace tools
}  // namespace mqas
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::mqas::tools::proto::ReqSendFileRet_Code_internal_data_>
    internal::EnumTraitsImpl::value<::mqas::tools::proto::ReqSendFileRet_Code>;
}  // namespace protobuf
}  // namespace google

namespace mqas {
namespace tools {
namespace proto {
enum ReqSendFileRet_Code : int {
  ReqSendFileRet_Code_ok = 0,
  ReqSendFileRet_Code_already_exists = 1,
  ReqSendFileRet_Code_open_failed = 2,
  ReqSendFileRet_Code_write_failed = 3,
  ReqSendFileRet_Code_close_failed = 4,
  ReqSendFileRet_Code_md5_not_same = 5,
  ReqSendFileRet_Code_ReqSendFileRet_Code_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  ReqSendFileRet_Code_ReqSendFileRet_Code_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

MQAS_EXTERN extern const uint32_t ReqSendFileRet_Code_internal_data_[];
inline constexpr ReqSendFileRet_Code ReqSendFileRet_Code_Code_MIN =
    static_cast<ReqSendFileRet_Code>(0);
inline constexpr ReqSendFileRet_Code ReqSendFileRet_Code_Code_MAX =
    static_cast<ReqSendFileRet_Code>(5);
inline bool ReqSendFileRet_Code_IsValid(int value) {
  return 0 <= value && value <= 5;
}
inline constexpr int ReqSendFileRet_Code_Code_ARRAYSIZE = 5 + 1;
MQAS_EXTERN const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ReqSendFileRet_Code_descriptor();
template <typename T>
const std::string& ReqSendFileRet_Code_Name(T value) {
  static_assert(std::is_same<T, ReqSendFileRet_Code>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to Code_Name().");
  return ReqSendFileRet_Code_Name(static_cast<ReqSendFileRet_Code>(value));
}
template <>
inline const std::string& ReqSendFileRet_Code_Name(ReqSendFileRet_Code value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ReqSendFileRet_Code_descriptor, 0, 5>(
      static_cast<int>(value));
}
inline bool ReqSendFileRet_Code_Parse(
    absl::string_view name, ReqSendFileRet_Code* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<ReqSendFileRet_Code>(ReqSendFileRet_Code_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class MQAS_EXTERN SendFileEnd final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mqas.tools.proto.SendFileEnd) */ {
 public:
  inline SendFileEnd() : SendFileEnd(nullptr) {}
  ~SendFileEnd() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SendFileEnd* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SendFileEnd));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SendFileEnd(::google::protobuf::internal::ConstantInitialized);

  inline SendFileEnd(const SendFileEnd& from) : SendFileEnd(nullptr, from) {}
  inline SendFileEnd(SendFileEnd&& from) noexcept
      : SendFileEnd(nullptr, std::move(from)) {}
  inline SendFileEnd& operator=(const SendFileEnd& from) {
    CopyFrom(from);
    return *this;
  }
  inline SendFileEnd& operator=(SendFileEnd&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SendFileEnd& default_instance() {
    return *reinterpret_cast<const SendFileEnd*>(
        &_SendFileEnd_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(SendFileEnd& a, SendFileEnd& b) { a.Swap(&b); }
  inline void Swap(SendFileEnd* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SendFileEnd* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SendFileEnd* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SendFileEnd>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SendFileEnd& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SendFileEnd& from) { SendFileEnd::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SendFileEnd* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mqas.tools.proto.SendFileEnd"; }

 protected:
  explicit SendFileEnd(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SendFileEnd(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SendFileEnd& from);
  SendFileEnd(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SendFileEnd&& from) noexcept
      : SendFileEnd(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 1,
    kMd5FieldNumber = 2,
  };
  // string name = 1;
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // bytes md5 = 2;
  void clear_md5() ;
  const std::string& md5() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_md5(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_md5();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_md5();
  void set_allocated_md5(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_md5() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_md5(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_md5();

  public:
  // @@protoc_insertion_point(class_scope:mqas.tools.proto.SendFileEnd)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 41,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SendFileEnd& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::google::protobuf::internal::ArenaStringPtr md5_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_send_5ffile_2eproto;
};

MQAS_EXTERN extern const ::google::protobuf::internal::ClassDataFull SendFileEnd_class_data_;
// -------------------------------------------------------------------

class MQAS_EXTERN ReqSendFileRet final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mqas.tools.proto.ReqSendFileRet) */ {
 public:
  inline ReqSendFileRet() : ReqSendFileRet(nullptr) {}
  ~ReqSendFileRet() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ReqSendFileRet* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ReqSendFileRet));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ReqSendFileRet(::google::protobuf::internal::ConstantInitialized);

  inline ReqSendFileRet(const ReqSendFileRet& from) : ReqSendFileRet(nullptr, from) {}
  inline ReqSendFileRet(ReqSendFileRet&& from) noexcept
      : ReqSendFileRet(nullptr, std::move(from)) {}
  inline ReqSendFileRet& operator=(const ReqSendFileRet& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReqSendFileRet& operator=(ReqSendFileRet&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReqSendFileRet& default_instance() {
    return *reinterpret_cast<const ReqSendFileRet*>(
        &_ReqSendFileRet_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ReqSendFileRet& a, ReqSendFileRet& b) { a.Swap(&b); }
  inline void Swap(ReqSendFileRet* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReqSendFileRet* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReqSendFileRet* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ReqSendFileRet>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ReqSendFileRet& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ReqSendFileRet& from) { ReqSendFileRet::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ReqSendFileRet* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mqas.tools.proto.ReqSendFileRet"; }

 protected:
  explicit ReqSendFileRet(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ReqSendFileRet(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ReqSendFileRet& from);
  ReqSendFileRet(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ReqSendFileRet&& from) noexcept
      : ReqSendFileRet(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Code = ReqSendFileRet_Code;
  static constexpr Code ok = ReqSendFileRet_Code_ok;
  static constexpr Code already_exists = ReqSendFileRet_Code_already_exists;
  static constexpr Code open_failed = ReqSendFileRet_Code_open_failed;
  static constexpr Code write_failed = ReqSendFileRet_Code_write_failed;
  static constexpr Code close_failed = ReqSendFileRet_Code_close_failed;
  static constexpr Code md5_not_same = ReqSendFileRet_Code_md5_not_same;
  static inline bool Code_IsValid(int value) {
    return ReqSendFileRet_Code_IsValid(value);
  }
  static constexpr Code Code_MIN = ReqSendFileRet_Code_Code_MIN;
  static constexpr Code Code_MAX = ReqSendFileRet_Code_Code_MAX;
  static constexpr int Code_ARRAYSIZE = ReqSendFileRet_Code_Code_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Code_descriptor() {
    return ReqSendFileRet_Code_descriptor();
  }
  template <typename T>
  static inline const std::string& Code_Name(T value) {
    return ReqSendFileRet_Code_Name(value);
  }
  static inline bool Code_Parse(
      absl::string_view name, Code* PROTOBUF_NONNULL value) {
    return ReqSendFileRet_Code_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kCodeFieldNumber = 1,
    kErrorCodeFieldNumber = 2,
  };
  // .mqas.tools.proto.ReqSendFileRet.Code code = 1;
  void clear_code() ;
  ::mqas::tools::proto::ReqSendFileRet_Code code() const;
  void set_code(::mqas::tools::proto::ReqSendFileRet_Code value);

  private:
  ::mqas::tools::proto::ReqSendFileRet_Code _internal_code() const;
  void _internal_set_code(::mqas::tools::proto::ReqSendFileRet_Code value);

  public:
  // optional sint32 error_code = 2;
  bool has_error_code() const;
  void clear_error_code() ;
  ::int32_t error_code() const;
  void set_error_code(::int32_t value);

  private:
  ::int32_t _internal_error_code() const;
  void _internal_set_error_code(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:mqas.tools.proto.ReqSendFileRet)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ReqSendFileRet& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    int code_;
    ::int32_t error_code_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_send_5ffile_2eproto;
};

MQAS_EXTERN extern const ::google::protobuf::internal::ClassDataFull ReqSendFileRet_class_data_;
// -------------------------------------------------------------------

class MQAS_EXTERN ReqSendFile final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mqas.tools.proto.ReqSendFile) */ {
 public:
  inline ReqSendFile() : ReqSendFile(nullptr) {}
  ~ReqSendFile() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ReqSendFile* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ReqSendFile));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ReqSendFile(::google::protobuf::internal::ConstantInitialized);

  inline ReqSendFile(const ReqSendFile& from) : ReqSendFile(nullptr, from) {}
  inline ReqSendFile(ReqSendFile&& from) noexcept
      : ReqSendFile(nullptr, std::move(from)) {}
  inline ReqSendFile& operator=(const ReqSendFile& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReqSendFile& operator=(ReqSendFile&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReqSendFile& default_instance() {
    return *reinterpret_cast<const ReqSendFile*>(
        &_ReqSendFile_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ReqSendFile& a, ReqSendFile& b) { a.Swap(&b); }
  inline void Swap(ReqSendFile* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReqSendFile* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReqSendFile* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ReqSendFile>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ReqSendFile& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ReqSendFile& from) { ReqSendFile::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ReqSendFile* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mqas.tools.proto.ReqSendFile"; }

 protected:
  explicit ReqSendFile(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ReqSendFile(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ReqSendFile& from);
  ReqSendFile(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ReqSendFile&& from) noexcept
      : ReqSendFile(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 1,
    kSizeFieldNumber = 2,
    kBufSizeFieldNumber = 3,
    kOverlayFieldNumber = 4,
  };
  // string name = 1;
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // uint64 size = 2;
  void clear_size() ;
  ::uint64_t size() const;
  void set_size(::uint64_t value);

  private:
  ::uint64_t _internal_size() const;
  void _internal_set_size(::uint64_t value);

  public:
  // uint32 buf_size = 3;
  void clear_buf_size() ;
  ::uint32_t buf_size() const;
  void set_buf_size(::uint32_t value);

  private:
  ::uint32_t _internal_buf_size() const;
  void _internal_set_buf_size(::uint32_t value);

  public:
  // bool overlay = 4;
  void clear_overlay() ;
  bool overlay() const;
  void set_overlay(bool value);

  private:
  bool _internal_overlay() const;
  void _internal_set_overlay(bool value);

  public:
  // @@protoc_insertion_point(class_scope:mqas.tools.proto.ReqSendFile)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 41,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ReqSendFile& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::uint64_t size_;
    ::uint32_t buf_size_;
    bool overlay_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_send_5ffile_2eproto;
};

MQAS_EXTERN extern const ::google::protobuf::internal::ClassDataFull ReqSendFile_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ReqSendFile

// string name = 1;
inline void ReqSendFile::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ReqSendFile::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mqas.tools.proto.ReqSendFile.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ReqSendFile::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mqas.tools.proto.ReqSendFile.name)
}
inline std::string* PROTOBUF_NONNULL ReqSendFile::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:mqas.tools.proto.ReqSendFile.name)
  return _s;
}
inline const std::string& ReqSendFile::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void ReqSendFile::_internal_set_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL ReqSendFile::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.name_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE ReqSendFile::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mqas.tools.proto.ReqSendFile.name)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void ReqSendFile::set_allocated_name(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mqas.tools.proto.ReqSendFile.name)
}

// uint64 size = 2;
inline void ReqSendFile::clear_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.size_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::uint64_t ReqSendFile::size() const {
  // @@protoc_insertion_point(field_get:mqas.tools.proto.ReqSendFile.size)
  return _internal_size();
}
inline void ReqSendFile::set_size(::uint64_t value) {
  _internal_set_size(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:mqas.tools.proto.ReqSendFile.size)
}
inline ::uint64_t ReqSendFile::_internal_size() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.size_;
}
inline void ReqSendFile::_internal_set_size(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.size_ = value;
}

// uint32 buf_size = 3;
inline void ReqSendFile::clear_buf_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.buf_size_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::uint32_t ReqSendFile::buf_size() const {
  // @@protoc_insertion_point(field_get:mqas.tools.proto.ReqSendFile.buf_size)
  return _internal_buf_size();
}
inline void ReqSendFile::set_buf_size(::uint32_t value) {
  _internal_set_buf_size(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:mqas.tools.proto.ReqSendFile.buf_size)
}
inline ::uint32_t ReqSendFile::_internal_buf_size() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.buf_size_;
}
inline void ReqSendFile::_internal_set_buf_size(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.buf_size_ = value;
}

// bool overlay = 4;
inline void ReqSendFile::clear_overlay() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.overlay_ = false;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline bool ReqSendFile::overlay() const {
  // @@protoc_insertion_point(field_get:mqas.tools.proto.ReqSendFile.overlay)
  return _internal_overlay();
}
inline void ReqSendFile::set_overlay(bool value) {
  _internal_set_overlay(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:mqas.tools.proto.ReqSendFile.overlay)
}
inline bool ReqSendFile::_internal_overlay() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.overlay_;
}
inline void ReqSendFile::_internal_set_overlay(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.overlay_ = value;
}

// -------------------------------------------------------------------

// ReqSendFileRet

// .mqas.tools.proto.ReqSendFileRet.Code code = 1;
inline void ReqSendFileRet::clear_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::mqas::tools::proto::ReqSendFileRet_Code ReqSendFileRet::code() const {
  // @@protoc_insertion_point(field_get:mqas.tools.proto.ReqSendFileRet.code)
  return _internal_code();
}
inline void ReqSendFileRet::set_code(::mqas::tools::proto::ReqSendFileRet_Code value) {
  _internal_set_code(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:mqas.tools.proto.ReqSendFileRet.code)
}
inline ::mqas::tools::proto::ReqSendFileRet_Code ReqSendFileRet::_internal_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::mqas::tools::proto::ReqSendFileRet_Code>(_impl_.code_);
}
inline void ReqSendFileRet::_internal_set_code(::mqas::tools::proto::ReqSendFileRet_Code value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_ = value;
}

// optional sint32 error_code = 2;
inline bool ReqSendFileRet::has_error_code() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void ReqSendFileRet::clear_error_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_code_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t ReqSendFileRet::error_code() const {
  // @@protoc_insertion_point(field_get:mqas.tools.proto.ReqSendFileRet.error_code)
  return _internal_error_code();
}
inline void ReqSendFileRet::set_error_code(::int32_t value) {
  _internal_set_error_code(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:mqas.tools.proto.ReqSendFileRet.error_code)
}
inline ::int32_t ReqSendFileRet::_internal_error_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.error_code_;
}
inline void ReqSendFileRet::_internal_set_error_code(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_code_ = value;
}

// -------------------------------------------------------------------

// SendFileEnd

// string name = 1;
inline void SendFileEnd::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& SendFileEnd::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mqas.tools.proto.SendFileEnd.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SendFileEnd::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mqas.tools.proto.SendFileEnd.name)
}
inline std::string* PROTOBUF_NONNULL SendFileEnd::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:mqas.tools.proto.SendFileEnd.name)
  return _s;
}
inline const std::string& SendFileEnd::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void SendFileEnd::_internal_set_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL SendFileEnd::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.name_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE SendFileEnd::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mqas.tools.proto.SendFileEnd.name)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void SendFileEnd::set_allocated_name(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mqas.tools.proto.SendFileEnd.name)
}

// bytes md5 = 2;
inline void SendFileEnd::clear_md5() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.md5_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& SendFileEnd::md5() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mqas.tools.proto.SendFileEnd.md5)
  return _internal_md5();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SendFileEnd::set_md5(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.md5_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mqas.tools.proto.SendFileEnd.md5)
}
inline std::string* PROTOBUF_NONNULL SendFileEnd::mutable_md5()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_md5();
  // @@protoc_insertion_point(field_mutable:mqas.tools.proto.SendFileEnd.md5)
  return _s;
}
inline const std::string& SendFileEnd::_internal_md5() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.md5_.Get();
}
inline void SendFileEnd::_internal_set_md5(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.md5_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL SendFileEnd::_internal_mutable_md5() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.md5_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE SendFileEnd::release_md5() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mqas.tools.proto.SendFileEnd.md5)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.md5_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.md5_.Set("", GetArena());
  }
  return released;
}
inline void SendFileEnd::set_allocated_md5(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.md5_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.md5_.IsDefault()) {
    _impl_.md5_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mqas.tools.proto.SendFileEnd.md5)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace tools
}  // namespace mqas


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::mqas::tools::proto::ReqSendFileRet_Code> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::mqas::tools::proto::ReqSendFileRet_Code>() {
  return ::mqas::tools::proto::ReqSendFileRet_Code_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // send_5ffile_2eproto_2epb_2eh
