# syntax=docker/dockerfile:1
FROM ey1274704958/p2p_ser_t:latest

CMD ["bash", "-c", "cd /root/code/test_xquic && rm -rf build-linux && mkdir build-linux && cd build-linux && cmake -DBUILD_MQAS_EXAMPLES=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/root/code/vcpkg/scripts/buildsystems/vcpkg.cmake .. && make test_p2p_ser && cd examples/test_p2p_ser/ && ./test_p2p_ser"]

EXPOSE 27 8084 8085
