// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_wrapper.proto

#include "mqas/core/proto/msg_wrapper.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace mqas {
namespace core {
namespace proto {
PROTOBUF_CONSTEXPR MsgWrapper::MsgWrapper(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.msg_body_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.msg_id_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MsgWrapperDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MsgWrapperDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MsgWrapperDefaultTypeInternal() {}
  union {
    MsgWrapper _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MsgWrapperDefaultTypeInternal _MsgWrapper_default_instance_;
}  // namespace proto
}  // namespace core
}  // namespace mqas
static ::_pb::Metadata file_level_metadata_msg_5fwrapper_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_msg_5fwrapper_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_msg_5fwrapper_2eproto = nullptr;

const uint32_t TableStruct_msg_5fwrapper_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mqas::core::proto::MsgWrapper, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mqas::core::proto::MsgWrapper, _impl_.msg_id_),
  PROTOBUF_FIELD_OFFSET(::mqas::core::proto::MsgWrapper, _impl_.msg_body_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::mqas::core::proto::MsgWrapper)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::mqas::core::proto::_MsgWrapper_default_instance_._instance,
};

const char descriptor_table_protodef_msg_5fwrapper_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021msg_wrapper.proto\022\017mqas.core.proto\".\n\n"
  "MsgWrapper\022\016\n\006msg_id\030\001 \001(\r\022\020\n\010msg_body\030\002"
  " \001(\014b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_msg_5fwrapper_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_msg_5fwrapper_2eproto = {
    false, false, 92, descriptor_table_protodef_msg_5fwrapper_2eproto,
    "msg_wrapper.proto",
    &descriptor_table_msg_5fwrapper_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_msg_5fwrapper_2eproto::offsets,
    file_level_metadata_msg_5fwrapper_2eproto, file_level_enum_descriptors_msg_5fwrapper_2eproto,
    file_level_service_descriptors_msg_5fwrapper_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_msg_5fwrapper_2eproto_getter() {
  return &descriptor_table_msg_5fwrapper_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_msg_5fwrapper_2eproto(&descriptor_table_msg_5fwrapper_2eproto);
namespace mqas {
namespace core {
namespace proto {

// ===================================================================

class MsgWrapper::_Internal {
 public:
};

MsgWrapper::MsgWrapper(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mqas.core.proto.MsgWrapper)
}
MsgWrapper::MsgWrapper(const MsgWrapper& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MsgWrapper* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.msg_body_){}
    , decltype(_impl_.msg_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.msg_body_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.msg_body_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_msg_body().empty()) {
    _this->_impl_.msg_body_.Set(from._internal_msg_body(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.msg_id_ = from._impl_.msg_id_;
  // @@protoc_insertion_point(copy_constructor:mqas.core.proto.MsgWrapper)
}

inline void MsgWrapper::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.msg_body_){}
    , decltype(_impl_.msg_id_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.msg_body_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.msg_body_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

MsgWrapper::~MsgWrapper() {
  // @@protoc_insertion_point(destructor:mqas.core.proto.MsgWrapper)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MsgWrapper::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.msg_body_.Destroy();
}

void MsgWrapper::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MsgWrapper::Clear() {
// @@protoc_insertion_point(message_clear_start:mqas.core.proto.MsgWrapper)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.msg_body_.ClearToEmpty();
  _impl_.msg_id_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MsgWrapper::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 msg_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.msg_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes msg_body = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_msg_body();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MsgWrapper::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mqas.core.proto.MsgWrapper)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 msg_id = 1;
  if (this->_internal_msg_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_msg_id(), target);
  }

  // bytes msg_body = 2;
  if (!this->_internal_msg_body().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_msg_body(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mqas.core.proto.MsgWrapper)
  return target;
}

size_t MsgWrapper::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mqas.core.proto.MsgWrapper)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes msg_body = 2;
  if (!this->_internal_msg_body().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_msg_body());
  }

  // uint32 msg_id = 1;
  if (this->_internal_msg_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_msg_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MsgWrapper::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MsgWrapper::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MsgWrapper::GetClassData() const { return &_class_data_; }


void MsgWrapper::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MsgWrapper*>(&to_msg);
  auto& from = static_cast<const MsgWrapper&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mqas.core.proto.MsgWrapper)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_msg_body().empty()) {
    _this->_internal_set_msg_body(from._internal_msg_body());
  }
  if (from._internal_msg_id() != 0) {
    _this->_internal_set_msg_id(from._internal_msg_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MsgWrapper::CopyFrom(const MsgWrapper& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mqas.core.proto.MsgWrapper)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgWrapper::IsInitialized() const {
  return true;
}

void MsgWrapper::InternalSwap(MsgWrapper* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.msg_body_, lhs_arena,
      &other->_impl_.msg_body_, rhs_arena
  );
  swap(_impl_.msg_id_, other->_impl_.msg_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata MsgWrapper::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_msg_5fwrapper_2eproto_getter, &descriptor_table_msg_5fwrapper_2eproto_once,
      file_level_metadata_msg_5fwrapper_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace core
}  // namespace mqas
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::mqas::core::proto::MsgWrapper*
Arena::CreateMaybeMessage< ::mqas::core::proto::MsgWrapper >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mqas::core::proto::MsgWrapper >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
