# More comprehensive shared library judgment function
function(check_target_is_shared target result_var)
    if(NOT TARGET ${target})
        #message(WARNING "Target ${target} does not exist")
        set(${result_var} OFF PARENT_SCOPE)
        return()
    endif()

    get_target_property(target_type ${target} TYPE)
    get_target_property(target_imported ${target} IMPORTED)
    get_target_property(target_shared ${target} SHARED_LIBRARY)

    #message(STATUS "Target: ${target}")
    #message(STATUS "  TYPE: ${target_type}")
    #message(STATUS "  IMPORTED: ${target_imported}")
    #message(STATUS "  SHARED_LIBRARY: ${target_shared}")

    if(target_type STREQUAL "SHARED_LIBRARY")
        #message(STATUS "  → This is a shared library")
        set(${result_var} ON PARENT_SCOPE)
        return()
    elseif(target_type STREQUAL "MODULE_LIBRARY")
        #message(STATUS "  → This is a module library (also a type of shared library)")
        set(${result_var} ON PARENT_SCOPE)
        return()
    elseif(target_type STREQUAL "STATIC_LIBRARY")
        #message(STATUS "  → This is a static library")
        set(${result_var} OFF PARENT_SCOPE)
        return()
    elseif(target_type STREQUAL "EXECUTABLE")
        #message(STATUS "  → This is an executable file")
        set(${result_var} OFF PARENT_SCOPE)
        return()
    elseif(target_imported)
        # For imported libraries, need further checking
        get_target_property(imported_location ${target} IMPORTED_LOCATION)
        get_target_property(imported_type ${target} IMPORTED_TYPE)

        if(imported_location)
            if(imported_location MATCHES "\\.(so|dylib|dll)$")
                #message(STATUS "  → This is an imported shared library")
                set(${result_var} ON PARENT_SCOPE)
                return()
            else()
                #message(STATUS "  → This is an imported static library")
                set(${result_var} OFF PARENT_SCOPE)
                return()
            endif()
        endif()
        set(${result_var} OFF PARENT_SCOPE)
        return()
    else()
        #message(STATUS "  → Unknown type")
        set(${result_var} OFF PARENT_SCOPE)
        return()
    endif()
endfunction()