message("Find xquic")

if(NOT XQUIC_PATH)
    message("No XQUIC_PATH find")
    find_path(xquic_INCLUDE_DIR xquic REQUIED)
    find_library(xquic_LIBRARY xquic REQUIED)
else()
    message("${XQUIC_PATH}/include")

    if(CMAKE_BUILD_TYPE STREQUAL "Release")
        set(Lib_Relative_Dir "build/x64-Release")
    elseif(CMAKE_BUILD_TYPE STREQUAL "Debug")
        set(Lib_Relative_Dir "build/x64-Debug")
    endif()
    message("${XQUIC_PATH}/${Lib_Relative_Dir}")
    find_path(xquic_INCLUDE_DIR xquic "${XQUIC_PATH}/include" REQUIED)
    find_library(xquic_LIBRARY xquic "${XQUIC_PATH}/${Lib_Relative_Dir}" REQUIED)
    if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
        find_path(xquic_BIN_DIR xquic.dll "${XQUIC_PATH}/${Lib_Relative_Dir}" REQUIED)
        #find_file(xquic_DLL_LIBRARY xquic.dll "${XQUIC_PATH}/${Lib_Relative_Dir}" REQUIED)
        #find_file(ssl_DLL_LIBRARY ssl.dll "${XQUIC_PATH}/${Lib_Relative_Dir}" REQUIED)
        #find_file(crypto_DLL_LIBRARY crypto.dll "${XQUIC_PATH}/${Lib_Relative_Dir}" REQUIED)
    endif()
    unset(Lib_Relative_Dir)
endif()
set(xquic_FOUND true)
message("xquic_INCLUDE_DIR = ${xquic_INCLUDE_DIR}")
message("xquic_LIBRARY = ${xquic_LIBRARY}")