syntax = "proto3";

package mqas.tools.proto.p2p;

//data
message PeerData {
    uint32 id = 1;
    string name = 2;
}

enum RetCode{
    ok = 0;
    already_exists = 1;
    not_exists = 2;
    peer_rejected = 3;
    failed = 4;
}

message ClientIpList{
    repeated string ip_list = 1;
    uint32 port = 2;
}

message Address {
    string ip = 1;
    uint32 port = 2;
}
//--------------------------------

//lobby 
message ReqPeerList{}

message RespondPeerList{
    repeated PeerData peer_list = 1;
}

message ReqRegistePeer{
    string name = 1;
}

message RespondRegistePeer{
    RetCode ret = 1;
    uint32 id = 2;
}

message ReqUnregistePeer{}

message RespondUnregistePeer{
    RetCode ret = 1;
}

//-------------------------------------

message ConnectPeerData{
    string ip = 1;
    uint32 port = 2;
    uint32 verify_code = 3;
    uint32 send_times = 4; 
    uint32 send_delay = 5;
    uint32 ip_index = 6;
}

//helper
message ReqConnectPeer{
    uint32 peer_id = 1;
    optional ClientIpList ip_list = 2;
}

message ReqRespondPeerReqConnect{
    uint32 peer_id = 1;
    bool agree = 2;
    optional ClientIpList ip_list = 3;
}

message RespondConnectPeer{
    uint32 peer_id = 1;
    RetCode ret = 2;
}

message NotifyConnectPeerData{
    uint32 peer_id = 1;
    ConnectPeerData connect_data = 2;
}

message NotifyConnectResult{
    RetCode ret = 1;
    uint32 peer_id = 2;
    bool is_server = 5;
    optional string reason = 3;
    optional Address address = 4;
}

message NotifyPeerWantConnect{
    PeerData peer = 1;
}

message ReqSubmitRecvPeerKeyCode{
    uint32 peer_id = 1;
    uint32 verify_code = 2;
    uint32 ip_index = 3;
}
//--------------------------------------------