syntax = "proto3";

package mqas.tools.proto.p2p_client;
import "common.proto";


enum RetCode{
    ok = 0;
    wrong_token = 1;
    already_connected = 2;
    token_not_found = 3;
    unknown_error = 4;
    not_submit_token = 5;
    refused_by_peer = 6;
    id_not_found = 7;
}

message RequestDirectConnect {
    common.UUID token = 1;
	string name = 2;
    uint32 peer_id = 3;
}

message RespondDirectConnect {
    RetCode code = 1;
	string name = 2;
	uint32 peer_id = 3;
}

message RequestDirectQuit {
    optional string reason = 1;
}

message RespondDirectQuit {
    RetCode code = 1;
}
